spring.application.name=demo
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/qlsv}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# T? ??ng t?o b?ng t? Java Entity (n?u c�)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
# 2. Thay vào đó, bật debug log riêng cho Hibernate SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# 3. Bật Log level của package dự án bạn
# Ví dụ thay com.JavaSpringBoot.BESpring bằng đúng tên gốc package của bạn
logging.level.com.JavaSpringBoot.BESpring=DEBUG

jwt.secret=${JWT_SECRET:phamminhhuy09012005tktayhoquangnamdanghocittaidanang}

file.upload-dir=uploads